create table if not exists public.misiones (
  idmision bigint primary key,
  titulo text not null,
  descripcion text not null,
  tipo text not null check (tipo in ('vida','situacion')),
  nivel_minimo numeric not null default 1,
  nivel_maximo numeric not null default 99,
  reputacion_minima numeric not null default 0,
  opcion1 text,
  respuesta1 text,
  resultado1 jsonb,
  opcion2 text,
  respuesta2 text,
  resultado2 jsonb,
  opcion3 text,
  respuesta3 text,
  resultado3 jsonb,
  created_at timestamptz not null default now()
);

insert into public.misiones (
  idmision, titulo, descripcion, tipo, nivel_minimo, nivel_maximo, reputacion_minima,
  opcion1, respuesta1, resultado1,
  opcion2, respuesta2, resultado2,
  opcion3, respuesta3, resultado3
) values
(
  1,
  'Pan robado en la aldea',
  'Un nino roba pan en el mercado. El panadero pide castigo.',
  'vida',
  1,
  99,
  0,
  'Pagar el pan con tus monedas.',
  NULL,
  '{"carisma": 1, "reputacion": 1}'::jsonb,
  'Perseguir al nino para recuperarlo.',
  NULL,
  '{"agilidad": 1, "vida": -4}'::jsonb,
  'Ignorar el conflicto y seguir camino.',
  NULL,
  '{"reputacion": -1}'::jsonb
),
(
  2,
  'Pozo contaminado',
  'El agua del pozo huele mal y los vecinos discuten.',
  'vida',
  1,
  99,
  0,
  'Bajar al pozo para limpiarlo.',
  NULL,
  '{"fuerza": 1, "vida": -5, "reputacion": 1}'::jsonb,
  'Convencer al herrero de ayudar.',
  NULL,
  '{"carisma": 1, "reputacion": 1}'::jsonb,
  'Cobrar por arreglar el problema.',
  NULL,
  '{"dano": 1, "reputacion": -2}'::jsonb
),
(
  3,
  'Duelo de taberna',
  'Dos mercenarios te retan por una vieja ofensa.',
  'vida',
  1,
  99,
  0,
  'Aceptar el duelo.',
  NULL,
  '{"dano": 1, "vida": -6, "reputacion": 1}'::jsonb,
  'Calmar la situacion con palabras.',
  NULL,
  '{"carisma": 2, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  4,
  'Carta sellada',
  'Un mensajero cae herido y te entrega una carta urgente.',
  'vida',
  1,
  99,
  0,
  'Llevar la carta sin abrirla.',
  NULL,
  '{"reputacion": 2}'::jsonb,
  'Abrirla para conocer el riesgo.',
  NULL,
  '{"agilidad": 1, "reputacion": -1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  5,
  'Puente roto',
  'La unica salida del valle esta parcialmente destruida.',
  'vida',
  1,
  99,
  0,
  'Repararlo con troncos.',
  NULL,
  '{"fuerza": 1, "defensa": 1, "vida": -4}'::jsonb,
  'Saltarlo por una roca estrecha.',
  NULL,
  '{"agilidad": 2, "vida": -6}'::jsonb,
  'Esperar a un grupo mas grande.',
  NULL,
  '{"reputacion": -1, "vida": 2}'::jsonb
),
(
  6,
  'Reliquia en ruinas',
  'En una capilla abandonada hay una reliquia sin guardian.',
  'vida',
  1,
  99,
  0,
  'Dejarla donde esta.',
  NULL,
  '{"reputacion": 2, "carisma": 1}'::jsonb,
  'Tomarla para venderla.',
  NULL,
  '{"dano": 1, "reputacion": -2}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  7,
  'Lluvia de flechas',
  'Bandidos emboscan una caravana frente a ti.',
  'vida',
  1,
  99,
  0,
  'Cargar de frente.',
  NULL,
  '{"fuerza": 1, "vida": -8, "reputacion": 1}'::jsonb,
  'Flanquear por el bosque.',
  NULL,
  '{"agilidad": 1, "dano": 1}'::jsonb,
  'Negociar una retirada.',
  NULL,
  '{"carisma": 1, "reputacion": 1}'::jsonb
),
(
  8,
  'Noche sin fogata',
  'La tormenta apaga tu campamento y baja la temperatura.',
  'vida',
  1,
  99,
  0,
  'Buscar refugio en una cueva.',
  NULL,
  '{"defensa": 1, "vida": -3}'::jsonb,
  'Mantener guardia toda la noche.',
  NULL,
  '{"agilidad": 1, "vida": -5, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  9,
  'Juramento del herrero',
  'Un herrero anciano ofrece entrenarte una tarde.',
  'vida',
  1,
  99,
  0,
  'Entrenar golpe y postura.',
  NULL,
  '{"dano": 1, "defensa": 1}'::jsonb,
  'Ayudarlo a vender armas.',
  NULL,
  '{"carisma": 1, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  10,
  'Campanas del monasterio',
  'El abad pide ayuda para transportar provisiones.',
  'vida',
  1,
  99,
  0,
  'Llevar los sacos solo.',
  NULL,
  '{"fuerza": 2, "vida": -4}'::jsonb,
  'Organizar voluntarios.',
  NULL,
  '{"carisma": 2, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  11,
  'Cueva de ecos',
  'Se oyen voces en una cueva con pasajes estrechos.',
  'vida',
  1,
  99,
  0,
  'Entrar con antorcha.',
  NULL,
  '{"defensa": 1, "vida": -4}'::jsonb,
  'Entrar en silencio total.',
  NULL,
  '{"agilidad": 2}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  12,
  'Mercado negro',
  'Un comerciante ofrece venenos y atajos peligrosos.',
  'vida',
  1,
  99,
  0,
  'Comprar un frasco de guerra.',
  NULL,
  '{"dano": 2, "reputacion": -1}'::jsonb,
  'Denunciar al comerciante.',
  NULL,
  '{"reputacion": 2, "carisma": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  13,
  'Mensaje codificado',
  'Te entregan un pergamino con simbolos extranos.',
  'vida',
  1,
  99,
  0,
  'Descifrarlo con paciencia.',
  NULL,
  '{"agilidad": 1, "carisma": 1}'::jsonb,
  'Romper el sello y actuar rapido.',
  NULL,
  '{"dano": 1, "reputacion": -1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  14,
  'Fuga en la fortaleza',
  'Un preso afirma ser inocente y pide ayuda.',
  'vida',
  1,
  99,
  0,
  'Investigar antes de actuar.',
  NULL,
  '{"carisma": 1, "defensa": 1}'::jsonb,
  'Liberarlo en secreto.',
  NULL,
  '{"agilidad": 1, "reputacion": -1}'::jsonb,
  'Entregarlo al capitan.',
  NULL,
  '{"reputacion": 1, "dano": 1}'::jsonb
),
(
  15,
  'Torreon en llamas',
  'Un incendio avanza por un viejo torreon.',
  'vida',
  1,
  99,
  0,
  'Entrar a rescatar a los atrapados.',
  NULL,
  '{"vida": -8, "reputacion": 3}'::jsonb,
  'Coordinar cubos desde afuera.',
  NULL,
  '{"carisma": 2, "reputacion": 2}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  16,
  'Juramento de sangre',
  'Un noble exige lealtad total a su casa.',
  'vida',
  1,
  99,
  0,
  'Aceptar el juramento.',
  NULL,
  '{"reputacion": 1, "defensa": 1}'::jsonb,
  'Rechazar y mantener libertad.',
  NULL,
  '{"dano": 1, "reputacion": -1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  17,
  'Sendero de cazadores',
  'Un grupo de cazadores pierde rastro de una bestia.',
  'vida',
  1,
  99,
  0,
  'Rastrear huellas profundas.',
  NULL,
  '{"agilidad": 1, "fuerza": 1}'::jsonb,
  'Tender una trampa con carnada.',
  NULL,
  '{"defensa": 1, "dano": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  18,
  'Robo en el santuario',
  'Desaparece una ofrenda de gran valor religioso.',
  'vida',
  1,
  99,
  0,
  'Perseguir al ladron por tejados.',
  NULL,
  '{"agilidad": 2, "vida": -4}'::jsonb,
  'Interrogar testigos en la plaza.',
  NULL,
  '{"carisma": 2, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  19,
  'Muralla derrumbada',
  'Una seccion de muralla cae y deja la ciudad expuesta.',
  'vida',
  1,
  99,
  0,
  'Defender la brecha tu solo.',
  NULL,
  '{"defensa": 2, "vida": -7}'::jsonb,
  'Evacuar civiles primero.',
  NULL,
  '{"carisma": 1, "reputacion": 2}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  20,
  'Pacto del bosque',
  'Druidas ofrecen ayuda a cambio de talar menos arboles.',
  'vida',
  1,
  99,
  0,
  'Apoyar su causa.',
  NULL,
  '{"reputacion": 2, "vida": 4}'::jsonb,
  'Priorizar madera para guerra.',
  NULL,
  '{"dano": 1, "reputacion": -2}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  21,
  'Paso del contrabandista',
  'Un guia ilegal conoce un atajo hacia el castillo.',
  'vida',
  1,
  99,
  0,
  'Usar el atajo de noche.',
  NULL,
  '{"agilidad": 1, "reputacion": -1}'::jsonb,
  'Tomar el camino oficial.',
  NULL,
  '{"defensa": 1, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  22,
  'Archivo prohibido',
  'La biblioteca real tiene un tomo sellado con cera negra.',
  'vida',
  1,
  99,
  0,
  'Leerlo en secreto.',
  NULL,
  '{"dano": 1, "carisma": -1}'::jsonb,
  'Entregarlo al escriba mayor.',
  NULL,
  '{"reputacion": 2, "carisma": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  23,
  'Escolta diplomatica',
  'Debes proteger a una embajadora hacia territorio hostil.',
  'vida',
  1,
  99,
  0,
  'Marchar rapido y discreto.',
  NULL,
  '{"agilidad": 1, "defensa": 1}'::jsonb,
  'Marchar lento y visible.',
  NULL,
  '{"carisma": 1, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  24,
  'Vigilia de medianoche',
  'Las campanas suenan sin causa en la noche cerrada.',
  'vida',
  1,
  99,
  0,
  'Subir al campanario.',
  NULL,
  '{"agilidad": 1, "vida": -3}'::jsonb,
  'Montar guardia en el patio.',
  NULL,
  '{"defensa": 1, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  25,
  'Tormenta de arena',
  'Una ventisca cubre la ruta y desorienta caravanas.',
  'vida',
  1,
  99,
  0,
  'Guiar con cuerdas entre dunas.',
  NULL,
  '{"carisma": 1, "vida": -4, "reputacion": 2}'::jsonb,
  'Acampar y esperar.',
  NULL,
  '{"vida": 3, "reputacion": -1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  26,
  'Tributo injusto',
  'El recaudador exige impuestos dobles a campesinos pobres.',
  'situacion',
  1,
  99,
  0,
  'Enfrentar al recaudador.',
  NULL,
  '{"fuerza": 1, "reputacion": 2}'::jsonb,
  'Negociar una rebaja.',
  NULL,
  '{"carisma": 2, "reputacion": 1}'::jsonb,
  'No intervenir.',
  NULL,
  '{"reputacion": -2}'::jsonb
),
(
  27,
  'Frontera helada',
  'Una patrulla queda aislada por nieve profunda.',
  'situacion',
  1,
  99,
  0,
  'Abrir camino con fuerza.',
  NULL,
  '{"fuerza": 1, "vida": -5}'::jsonb,
  'Enviar senales de humo.',
  NULL,
  '{"carisma": 1, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  28,
  'Bandera enemiga',
  'Aparece una bandera rival en tu territorio.',
  'situacion',
  1,
  99,
  0,
  'Quemarla en publico.',
  NULL,
  '{"reputacion": 1, "dano": 1}'::jsonb,
  'Guardar pruebas y reportar.',
  NULL,
  '{"defensa": 1, "carisma": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  29,
  'Botin repartido',
  'Tu escuadra discute por el reparto de botin.',
  'situacion',
  1,
  99,
  0,
  'Tomar la mayor parte por rango.',
  NULL,
  '{"dano": 1, "reputacion": -2}'::jsonb,
  'Repartir equitativamente.',
  NULL,
  '{"carisma": 2, "reputacion": 2}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  30,
  'Acero encantado',
  'Un armero itinerante ofrece mejorar tu hoja por un favor.',
  'situacion',
  1,
  99,
  0,
  'Aceptar y hacer el favor.',
  NULL,
  '{"dano": 2, "reputacion": -1}'::jsonb,
  'Rechazar tratos dudosos.',
  NULL,
  '{"defensa": 1, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  31,
  'Mina colapsada',
  'Mineros quedan atrapados tras un derrumbe.',
  'situacion',
  1,
  99,
  0,
  'Entrar a remover rocas.',
  NULL,
  '{"fuerza": 2, "vida": -7, "reputacion": 2}'::jsonb,
  'Dirigir rescate desde afuera.',
  NULL,
  '{"carisma": 1, "defensa": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  32,
  'Cosecha saqueada',
  'Ladrones nocturnos vacian graneros enteros.',
  'situacion',
  1,
  99,
  0,
  'Vigilar en los tejados.',
  NULL,
  '{"agilidad": 1, "dano": 1}'::jsonb,
  'Tender trampa en los caminos.',
  NULL,
  '{"defensa": 1, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  33,
  'Jurista corrupto',
  'Un juez local acepta sobornos a plena luz.',
  'situacion',
  1,
  99,
  0,
  'Exponerlo ante el consejo.',
  NULL,
  '{"carisma": 2, "reputacion": 2}'::jsonb,
  'Amenazarlo en privado.',
  NULL,
  '{"dano": 1, "reputacion": -1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  34,
  'Ritual en el pantano',
  'Un culto realiza un ritual cerca del poblado.',
  'situacion',
  1,
  99,
  0,
  'Interrumpir el ritual.',
  NULL,
  '{"defensa": 1, "vida": -6, "reputacion": 1}'::jsonb,
  'Observar y aprender.',
  NULL,
  '{"dano": 1, "agilidad": 1, "reputacion": -1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  35,
  'Rueda del molino',
  'La rueda principal se atasca y no hay harina.',
  'situacion',
  1,
  99,
  0,
  'Empujarla manualmente.',
  NULL,
  '{"fuerza": 1, "vida": -3}'::jsonb,
  'Coordinar turnos de trabajo.',
  NULL,
  '{"carisma": 1, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  36,
  'Asedio menor',
  'Un fuerte aliado sufre hostigamiento constante.',
  'situacion',
  1,
  99,
  0,
  'Romper el asedio con ataque frontal.',
  NULL,
  '{"dano": 2, "vida": -8}'::jsonb,
  'Cortar suministros del enemigo.',
  NULL,
  '{"agilidad": 1, "defensa": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  37,
  'Bestia en corrales',
  'Algo mata ganado durante la madrugada.',
  'situacion',
  1,
  99,
  0,
  'Hacer guardia con lanza.',
  NULL,
  '{"dano": 1, "defensa": 1}'::jsonb,
  'Seguir rastros hasta su guarida.',
  NULL,
  '{"agilidad": 2, "vida": -4}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  38,
  'Festival real',
  'El rey organiza juegos para medir nuevos talentos.',
  'situacion',
  1,
  99,
  0,
  'Competir en justa.',
  NULL,
  '{"fuerza": 1, "defensa": 1, "reputacion": 1}'::jsonb,
  'Ganar aliados en el banquete.',
  NULL,
  '{"carisma": 2, "reputacion": 2}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  39,
  'Mensajes falsos',
  'Circulan cartas falsas con tu sello personal.',
  'situacion',
  1,
  99,
  0,
  'Seguir al falsificador.',
  NULL,
  '{"agilidad": 1, "reputacion": 1}'::jsonb,
  'Publicar un desmentido oficial.',
  NULL,
  '{"carisma": 2, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  40,
  'Contrato sombrio',
  'Un noble te paga por eliminar a un rival politico.',
  'situacion',
  1,
  99,
  0,
  'Aceptar el contrato.',
  NULL,
  '{"dano": 2, "reputacion": -3}'::jsonb,
  'Rechazar y denunciarlo.',
  NULL,
  '{"reputacion": 3, "carisma": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  41,
  'Murmullo de traicion',
  'Un capitan aliado podria estar vendiendo rutas.',
  'situacion',
  1,
  99,
  0,
  'Confrontarlo en publico.',
  NULL,
  '{"reputacion": 1, "dano": 1}'::jsonb,
  'Seguirlo en secreto.',
  NULL,
  '{"agilidad": 1, "defensa": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  42,
  'Hoguera del norte',
  'Senales de auxilio arden en las colinas lejanas.',
  'situacion',
  1,
  99,
  0,
  'Responder de inmediato.',
  NULL,
  '{"vida": -6, "reputacion": 2}'::jsonb,
  'Reunir refuerzos primero.',
  NULL,
  '{"carisma": 1, "defensa": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  43,
  'Puerta sellada',
  'Una cripta antigua se abre bajo la ciudad.',
  'situacion',
  1,
  99,
  0,
  'Descender sin esperar.',
  NULL,
  '{"dano": 1, "vida": -5}'::jsonb,
  'Bendecir armas y escudos.',
  NULL,
  '{"defensa": 2, "reputacion": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  44,
  'Cisma del consejo',
  'Dos facciones nobles quieren tu apoyo.',
  'situacion',
  1,
  99,
  0,
  'Elegir una faccion fuerte.',
  NULL,
  '{"reputacion": 1, "dano": 1}'::jsonb,
  'Mediar para una tregua.',
  NULL,
  '{"carisma": 2, "reputacion": 2}'::jsonb,
  'Mantener neutralidad armada.',
  NULL,
  '{"defensa": 1}'::jsonb
),
(
  45,
  'Velo de niebla',
  'Una niebla espesa oculta sombras y ruidos extranos.',
  'situacion',
  1,
  99,
  0,
  'Avanzar con antorchas.',
  NULL,
  '{"defensa": 1, "vida": -4}'::jsonb,
  'Moverse sin luz para sorprender.',
  NULL,
  '{"agilidad": 2, "vida": -3}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  46,
  'Lanza quebrada',
  'Tu escuadra pierde armas en plena ruta de guerra.',
  'situacion',
  1,
  99,
  0,
  'Improvisar armas con madera.',
  NULL,
  '{"fuerza": 1, "dano": 1}'::jsonb,
  'Replegar y reforzar defensas.',
  NULL,
  '{"defensa": 2, "reputacion": -1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  47,
  'Campamento desertor',
  'Soldados desertores piden unirse a tu causa.',
  'situacion',
  1,
  99,
  0,
  'Aceptarlos bajo vigilancia.',
  NULL,
  '{"carisma": 1, "reputacion": 1}'::jsonb,
  'Rechazarlos por traicion.',
  NULL,
  '{"defensa": 1, "reputacion": -1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  48,
  'Rito de coronas',
  'Un templo ofrece bendicion antes de la batalla final.',
  'situacion',
  1,
  99,
  0,
  'Aceptar bendicion completa.',
  NULL,
  '{"vida": 8, "reputacion": 2}'::jsonb,
  'Rechazar y confiar en tu acero.',
  NULL,
  '{"dano": 2}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  49,
  'Alarma en la capital',
  'La capital sufre ataques simultaneos en varios barrios.',
  'situacion',
  1,
  99,
  0,
  'Defender barrio civil.',
  NULL,
  '{"reputacion": 3, "vida": -7}'::jsonb,
  'Golpear el centro enemigo.',
  NULL,
  '{"dano": 2, "fuerza": 1}'::jsonb,
  NULL,
  NULL,
  NULL
),
(
  50,
  'Umbral de leyenda',
  'Tu nombre ya suena en el reino. Falta el ultimo paso.',
  'situacion',
  1,
  99,
  0,
  'Buscar gloria en combate directo.',
  NULL,
  '{"dano": 2, "reputacion": 2, "vida": -6}'::jsonb,
  'Proteger al pueblo por encima del honor.',
  NULL,
  '{"defensa": 2, "carisma": 2, "reputacion": 3}'::jsonb,
  'Tomar una ruta estrategica y fria.',
  NULL,
  '{"agilidad": 2, "fuerza": 1, "reputacion": 1}'::jsonb
)
on conflict (idmision) do update set
  titulo = excluded.titulo,
  descripcion = excluded.descripcion,
  tipo = excluded.tipo,
  nivel_minimo = excluded.nivel_minimo,
  nivel_maximo = excluded.nivel_maximo,
  reputacion_minima = excluded.reputacion_minima,
  opcion1 = excluded.opcion1,
  respuesta1 = excluded.respuesta1,
  resultado1 = excluded.resultado1,
  opcion2 = excluded.opcion2,
  respuesta2 = excluded.respuesta2,
  resultado2 = excluded.resultado2,
  opcion3 = excluded.opcion3,
  respuesta3 = excluded.respuesta3,
  resultado3 = excluded.resultado3;
